### PR TITLE
Add campuses

### PR DESCRIPTION
**Pull request by kukuminer**
issue #130

### CODE REVIEW

**Comment by kukuminer** [comment]
Actually, I need to check the prof side of things.
The student side is ready though.

**Comment by kukuminer** [comment]
Just to clarify, @jonatanschroeder , the db should not support having the same section on multiple campuses, correct? For the section table, (course, letter, term) is still a unique constraint, and campus is an additional one. Therefore, the same section cannot exist on more than one campus at a time, correct? If it is supposed to, we will need to restructure things. 

I'm asking because if an applicant applies to a course that has a section at more than 1 campus, it will have different interest/qualification ratings, and that course may appear more than once for a professor since there are 2 distinct records in the application table for it. In other words, there is more than one application for a single course in a single term, one for each campus. **How should I go about displaying these on the professor side? I can add a campus column, that seems to be the simplest approach.** I think any other approach would involve restructuring the DB further, but I am open to ideas.

**Comment by jonatanschroeder** [comment]
> Just to clarify, @jonatanschroeder , the db should not support having the same section on multiple campuses, correct? For the section table, (course, letter, term) is still a unique constraint, and campus is an additional one. Therefore, the same section cannot exist on more than one campus at a time, correct? If it is supposed to, we will need to restructure things.

Yes, that is correct, each section is in a single campus. If we ever end up with a section that crosses campus (unlikely), we can always create pseudo-sections for those.

> I'm asking because if an applicant applies to a course that has a section at more than 1 campus, it will have different interest/qualification ratings, and that course may appear more than once for a professor since there are 2 distinct records in the application table for it. In other words, there is more than one application for a single course in a single term, one for each campus. **How should I go about displaying these on the professor side? I can add a campus column, that seems to be the simplest approach.** I think any other approach would involve restructuring the DB further, but I am open to ideas.

A campus column is good. Also make sure the campus is listed in the instructor page for a section in a prominent way (e.g., the heading).

**Comment by kukuminer** [comment]
Ok, I think it's ready now. Hopefully this doesn't conflict with profs seeing eachother's notes too much

**Comment by kukuminer** [comment]
@jonatanschroeder I'm still working on the bug fix for the race condition issue, I think it's caused by some async stuff. 

Anyway, I discovered something else interesting: the push-forward of applications (for individual courses) pushes forward for ALL courses, even ones that may not exist in the later semester. Is this a problem? Should I try to limit it? It does create a lot of entries in the application table, so maybe its not ideal, but if sections are added later then the application will be there. If I limit it, it will not push forward any application rows that don't have a course in the later semester at the time of the push. 


Also, since I forgot how it works in the meeting briefly: Whenever a termapplication is opened by an applicant, it calls the endpoint to see if it needs to push forward an application. If an app already exists, it skips and does nothing. If it doesn't, then it does the push-forward steps. This endpoint gets called twice because of React's dev mode, so this shouldn't be an issue in production. Nevertheless, I am working on fixing it in case it does somehow get called twice in production.

**Comment by kukuminer** [comment]
Bug should be fixed now, ready for review. I think there is probably a neater way with pgp to lock the table somehow, or with async. But I got this working now, the issue was to await the lock call.

**Review by jonatanschroeder — APPROVED** [review]

**Pull request merged**
